# IAM User access configuration
AWS_ACCESS_KEY="<AWS_ACCESS_KEY>"
AWS_SECRET_ACCESS_KEY="<AWS_SECRET_ACCESS_KEY>"
AWS_REGION="us-east-1"

# S3 Bucket for photo objects
PHOTOGALLERY_S3_BUCKET_NAME="<PHOTOGALLERY_S3_BUCKET_NAME>"

# MySQL Configuration
RDS_DB_HOSTNAME="<RDS_DB_HOSTNAME>"
RDS_DB_USERNAME='<RDS_DB_USERNAME>'
RDS_DB_PASSWORD='<RDS_DB_PASSWORD>'
RDS_DB_NAME='<RDS_DB_NAME>'

# DynamoDB Table
DYNAMODB_TABLE='<DYNAMODB_TABLE>'

###### INSERT NEW ENVIRONMENT VARIEABLES HERE ######


####################################################